### PR TITLE
YSHOP2-1137: RichText > Added missing features and fixed bugs

### PR DESCRIPTION
**Pull request by GhitaNektt**
## JIRA Ticket

[YSHOP2-1137](https://youcanshop.atlassian.net/browse/YSHOP2-1137)

## QA Steps

* [x] run pnpm install (New package added)
* [x] Add text to the editor and try to apply different styles

## Note

Leave empty when you have nothing to say

[YSHOP2-1137]: https://youcanshop.atlassian.net/browse/YSHOP2-1137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by eihabkhan1** [comment]
Can we enforce the font family to be `Mona Sans`
Screenshot 2023-12-18 at 5 53 48 PM

**Comment by eihabkhan1** [comment]
Is there a way for us to choose the programming language when using a code block?
Screenshot 2023-12-19 at 9 46 30 AM

**Comment by eihabkhan1** [comment]
In fullscreen mode it appears that the tooltip gets in the way of dropdown menus, any idea how we might fix that?

https://github.com/youcan-shop/youcan-ui/assets/143792300/352d307f-6faf-4e62-b486-264fad402d30

**Comment by eihabkhan1** [comment]
Video embed doesn't seem to work

Video link: https://www.youtube.com/watch?v=dQw4w9WgXcQ

Screenshot 2023-12-19 at 10 29 01 AM

**Comment by eihabkhan1** [comment]
Characters menu seems to have different widths and height for each of its children
Screenshot 2023-12-19 at 10 30 52 AM

**Comment by eihabkhan1** [comment]
Is there a way for us to increase the size of the current table

https://github.com/youcan-shop/youcan-ui/assets/143792300/528df0de-f702-4139-bd3c-17b2d0883604

**Comment by eihabkhan1** [comment]
Seems that if a table is the last node it doesn't allow the user to insert a new line upon clicking right after the table, i have to insert a new line using the keyboard

https://github.com/youcan-shop/youcan-ui/assets/143792300/5201003b-9db3-441b-b252-1eb5039d1e10

**Comment by mosarabi** [comment]
we need to know which button style active

**Review by mosarabi — APPROVED** [review]

**Pull request merged**
