### PR TITLE
YSHOP2-1165: fix sidebar issue

### PR DESCRIPTION
**Pull request by eihabkhan1**
## JIRA Ticket

[YSHOP2-1165](https://youcanshop.atlassian.net/browse/YSHOP2-1165)

## QA Steps

* [ ] Go to X and Y
* [ ] See TEXT in page Z

## Note

Leave empty when you have nothing to say

[YSHOP2-1165]: https://youcanshop.atlassian.net/browse/YSHOP2-1165?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by GhitaNektt** [comment]
When changing the direction to RTL the white border of the items doesn't change position
Screenshot 2023-12-20 at 12 31 19

**Comment by eihabkhan1** [comment]
> When changing the direction to RTL the white border of the items doesn't change position Screenshot 2023-12-20 at 12 31 19

Good catch @GhitaNektt 
@mosarabi I'll handle this since I worked on the RTL thingy

**Comment by eihabkhan1** [comment]
@GhitaNektt Fixed the RTL issue in https://github.com/youcan-shop/youcan-ui/pull/189/commits/dd63b8c0d11b2735353b18668dba6a366ec1dad8, @mosarabi Can you reduce the toggle animation for expanding/collapsing parent items from `0.25s` to `0.1s`

**Comment by GhitaNektt** [comment]
little round icons for subitems not showing in RTL
Screenshot 2023-12-20 at 15 10 00

Screenshot 2023-12-20 at 15 09 43

**Review by mosarabi — APPROVED** [review]

**Pull request merged**
